name: mc
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.1
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.1
  - freetype=2.14.1
  - ipykernel=6.30.1
  - ipympl=0.9.8
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.9
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.3.5
  - openjpeg=2.5.3
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pip=25.2
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.5
  - python=3.13.7
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - pyzmq=27.1.0
  - qhull=2020.2
  - qutip=5.2.2
  - readline=8.3
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - fonttools==4.61.0
      - imageio==2.37.2
      - llvmlite==0.45.1
      - matplotlib==3.10.7
      - numba==0.62.1
      - pandas==2.3.3
      - pillow==12.0.0
      - pytz==2025.2
      - tzdata==2025.2
prefix: /home/francesco/miniconda3/envs/mc
